# Change these first
owner: streampanel # Your GitHub organization or username, where this repository lives
repo: status.streampanel.net # The name of this repository

sites:
  - name: STREAMPANEL
    url: https://www.streampanel.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.streampanel.net
  # baseUrl: /your-repo-name
  logoUrl: https://cassets.streampanel.cloud/logo/round/svg/black-white.svg
  name: STREAMPANEL
  introTitle: "**STREAMPANEL Status**"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  #scripts:
  #  - src: https://raw.githubusercontent.com/streampanel/status.streampanel.net/master/assets/privacy.js
  i18n:
    footer: [Privacy](https://www.streampanel.net/kontakt/datenschutz/) - [Imprint](https://www.streampanel.net/kontakt/impressum/), Powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# More configuration here: https://upptime.js.org/docs/configuration/
