# Change these first
owner: streampanel # Your GitHub organization or username, where this repository lives
repo: status.streampanel.net # The name of this repository

sites:
  - name: Webseite
    url: https://www.streampanel.net
  - name: Kundencenter
    url: https://login.streampanel.net
  - name: Webhosting 
    url: $ENDPOINT_WEBHOSTING
  - name: Centova Cast / Dedicated 
    url: $ENDPOINT_CENTOVA_DEFAULT
  - name: Centova Cast / Cloud 
    url: $ENDPOINT_CENTOVA_CLOUD
  - name: Teamspeak 3 
    url: $ENDPOINT_TEAMSPEAK
  - name: Safeguard / Webradio & Webhosting 
    url: $ENDPOINT_SAFEGUARD
  - name: SP_Monitoring / Frankfurt
    url: $ENDPOINT_MONITORING_FRANKFURT
    expectedStatusCodes:
      - 403
  - name: SP_Monitoring / Warschau
    url: $ENDPOINT_MONITORING_WARSCHAU
    expectedStatusCodes:
      - 403
  - name: SP_Monitoring / London
    url: $ENDPOINT_MONITORING_LONDON
    expectedStatusCodes:
      - 403
  - name: SP_Monitoring / Straßburg
    url: $ENDPOINT_MONITORING_STRASSBURG
    expectedStatusCodes:
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.streampanel.net
  # baseUrl: /your-repo-name
  logoUrl: https://cassets.streampanel.cloud/logo/round/svg/black-white.svg
  name: STREAMPANEL
  introTitle: "**STREAMPANEL Status**"
  introMessage: Diese Statusseite gibt einige Bereiche in Echtzeit aus. In dringenden Fällen ist ein [Supportticket](https://www.streampanel.net/kontakt/) immer der schnellste Weg zur Proplemlösung.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  
  # Custom HEAD-Section
  customHeadHtml: "
    <script>var _mtm = window._mtm = window._mtm || [];
    _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='https://pw.streampanel.net/js/container_KVNJAR2p.js'; s.parentNode.insertBefore(g,s);</script>
    "
    
  # CSS Styles
  css: '
   a {
   	text-decoration: none;
    }
    '

i18n:
  footer: Powered by [Upptime](https://upptime.js.org) | [Privacy](https://www.streampanel.net/kontakt/datenschutz/) | [Imprint](https://www.streampanel.net/kontakt/impressum/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# More configuration here: https://upptime.js.org/docs/configuration/
