blank_issues_enabled: true
contact_links:
  - name: Direct Contact
    url: https://login.streampanel.net/submitticket.php?step=2&deptid=2&language=english
    about: Optimally, always create a support ticket. This is the fastest way to solve the problem!
  - name: Direkter Kontakt
    url: https://login.streampanel.net/submitticket.php?step=2&deptid=2&language=german
    about: Im Optimalfall erstellen Sie immer ein Supportticket. Dies ist der schnellste Weg zur Problemlösung!
